### ISSUE TITLE
Not required in Noetic anymore

### ISSUE THREAD

**Issue by Martin-Oehler** [tradr-project/static_transform_mux#2]
Hey,
just a heads-up. This should not be required in Noetic anymore, since all messages of all latching publishers are re-published (see ros/ros_comm#1544)

Best regards,
Martin

**Comment by peci1** [comment]
Thanks for letting me know. However, if you're unsure what system will the "consumers" of your bag files use, it is still better to use static_transform_mux because that will allow even users with Melodic to have proper transforms.
