### ISSUE TITLE
ERROR: cannot launch node of type [static_transform_mux/static_transform_mux]: static_transform_mux

### ISSUE THREAD

**Issue by wanghao1666** [tradr-project/static_transform_mux#3]
Hi!I think your solution might work for my error.But I'm just new to ROS,I don't know how to install your solution.Can you show me how to install it?

**Comment by tpet** [comment]
You can just git clone it into your workspace, build it, source it, and use it.

**Comment by peci1** [comment]
You can also install it via APT: `sudo apt install ros-melodic-static-transform-mux` (or `ros-noetic-static-transform-mux` if you're running on ROS Noetic).

**Comment by peci1** [comment]
Update: Noetic has not been released via `apt` yet. I triggered the release, so it should be available within a month or so.

**Comment by wanghao1666** [comment]
> You can also install it via APT: `sudo apt install ros-melodic-static-transform-mux` (or `ros-noetic-static-transform-mux` if you're running on ROS Noetic).

Thanks to answer！

**Comment by wanghao1666** [comment]
> You can also install it via APT: `sudo apt install ros-melodic-static-transform-mux` (or `ros-noetic-static-transform-mux` if you're running on ROS Noetic).

I tried this before,when I typed in`sudo apt install ros-melodic-static-transform-mux`, ERROR:`uable to locate package ros-melodic-static-transform-mux`

**Comment by peci1** [comment]
Did you perform the standard ROS Melodic installation steps? http://wiki.ros.org/melodic/Installation/Ubuntu

**Comment by wanghao1666** [comment]
> 

Yes, Melodic has  been released via apt yet? I can't install it via APT.

**Comment by peci1** [comment]
What system are you installing it at? X86 or ARM64? What operating system? Ubuntu 18.04 or some Debian/Arch...?

**Comment by wanghao1666** [comment]
> What system are you installing it at? X86 or ARM64? What operating system? Ubuntu 18.04 or some Debian/Arch...?

X86, ubuntu18.04

**Comment by peci1** [comment]
Then follow the installation guide I posted above. When you do, everything should work. Or post the exact error `apt` gives you.

**Comment by wanghao1666** [comment]
> 

Thank you for answering！

**Comment by wanghao1666** [comment]
> Then follow the installation guide I posted above. When you do, everything should work. Or post the exact error `apt` gives you.

Thank you for your answering ! I fact , this error occurred when I was running  subtchallange/tunnel_urban_reference_datasets . If I can't solve this problem, I'll try  osrf/subt.
